<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
  <style type="text/css">
    .header{ background-color: yellow; height: 50px;}
    .middle{ border: 5px solid red; height: 500px;}
    .footer{ background-color: pink; height: 50px;}

  </style>
</head>
<body>
  <div class="header">
    <h1>Main layout</h1>
  </div>
  <div class="middle">
    <h1>Main layout</h1>
  </div>
  <div class="footer">
    <h1>Main layout</h1>
  </div>
<?php echo $this->getContent();?>
</body>
</html>  